@startuml
package "PLC Hardware" {
 [S7-1500] --> [Remote IO] 
 [Delta HMI] --> [S7-1500]
 [Remote IO] --> [IO Cards]

}

node "Hydraulic" {

frame "electromechanical"{
[relay]-->[hydraulic valves]
[hydraulic valves]-->[Hydraulic cylinder]
}

[hydraulic pump] -->[hydraulic pressure]
}

node "electric"{
 frame "Sensors"{
[Limit Switches] --> [sensor datas]
[pressure sensor]--> [sensor datas]
[vibration sensor]--> [sensor datas]
[temperature sensor]--> [sensor datas]
}
 frame "electrical actuator"{
  [S7-1500]-->[SINAMICS S120/G120]
  [SINAMICS S120/G120]-->[hydraulic pump motor]
  
  [IO Cards]-->[relay]

  
 }
}




database "Program" {
  folder "data acquisition" {
   [sensor datas] -->[S7-1500]
   [S7-1500 program]-->[S7-1500]
  }
  folder "HMI program" {
    [Delta HMI program] -->[S7-1500 program]
  }
}
@enduml