@startuml
[S7-1500] 
 [Delta_HMI] 
 

[Remote_IO_Cards]<--[Digital_input]
[Remote_IO_Cards]<--[Analog_input]
[Remote_IO_Cards]-->[Digital_output]
[Digital_output]-->[Relay]
[Buttons]--> [Digital_input]




[Hydraulic_Cylinder]
[Hydraulic_Pump] 
[Hydraulic_Pressure]
[SINAMICS_S120_G120]-->[Electrical_Motor]
[Electrical_Motor]-->[Hydraulic_Pump]
[Hydraulic_Pump]-- [Hydraulic_Pressure]
[Relay]--[Hydraulic_Valves]
[Hydraulic_Valves]--[Hydraulic_Cylinder]
[Hydraulic_Pressure]--[Hydraulic_Valves]

[Limit_Switches] --> [Digital_input]
[Pressure_Sensor] --> [Analog_input]
[Vibration_Sensor] --> [Analog_input]
[Temperature_Sensor]--> [Analog_input]



[SINAMICS_S120_G120]
[Relay]




[Delta_HMI] --  [S7-1500] :TCP/IP
[S7-1500]--[Remote_IO_Cards]:TCP/IP
[S7-1500]--[SINAMICS_S120_G120]:TCP/IP
[S7-1500]-->[IO_Data_Record_CSV]
[IO_Data_Record_CSV]-->[Python_DecisionTreeRegressor_Model]
[Python_DecisionTreeRegressor_Model]<---[PLC_input_simulation]
[Python_DecisionTreeRegressor_Model]--->[PLC_output_simulation]
@enduml
